name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ] # 监听 main 分支的推送
  workflow_dispatch:   # 支持手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to HF Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 请将下方的 YOUR_HF_USERNAME 替换为你的抱脸用户名，YOUR_SPACE_NAME 替换为你刚创建的 Space 名称
          git remote add hf https://cjem:$HF_TOKEN@huggingface.co/spaces/cjem/cjem/my-proxy
          git push -f hf main
